### ISSUE TITLE
UPDATE the README file 

### ISSUE THREAD

**Issue by aprameyakatti** [school-zone/School-Management-System-SMS-#7]
AS
A new USER who is new to project should be able to understand and work on the project

DESCRIBE 
the steps to install the repo

**Comment by MadhuMPandurangi** [comment]
@aprameyakatti I will take this issue.

**Comment by aprameyakatti** [comment]
okay I will assign you

**Comment by MadhuMPandurangi** [comment]
### Updated and issue solved
Updated file has been merged and can view in the commit #8

**Comment by aprameyakatti** [comment]
good madhu great job.......
